In [77]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', None)
import seaborn as sns

In [86]:
business_map = pd.read_excel('./data/aXbEgwNzAtUpwpLRuxhcLt.xlsx')

In [89]:
business_map['name']

0                        m_start
1                          m_end
2                        m_today
3                     m_username
4                     m_deviceid
                 ...
121    m_biz_unn_membrshps_other
122                          NaN
123                       note_3
124                  __version__
125                    _version_
Name: name, Length: 126, dtype: object

In [83]:
business_map.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   type                              126 non-null    object
 1   name                              116 non-null    object
 2   label::English (en)               105 non-null    object
 3   label::नेपाली (ne)                1 non-null      object
 4   hint::English (en)                9 non-null      object
 5   hint::नेपाली (ne)                 0 non-null      float64
 6   required                          87 non-null     float64
 7   required_message::English (en)    87 non-null     object
 8   required_message::नेपाली (ne)     0 non-null      float64
 9   relevant                          58 non-null     object
 10  constraint                        19 non-null     object
 11  constraint_message::English (en)  14 non-null     object
 12  constraint_message::नेपाली (ne)   0 non-null      float64
 13  choice_filter                     7 non-null      object
 14  appearance                        4 non-null      object
 15  accuracyThreshold                 1 non-null      float64
 16  calculation                       2 non-null      object
 17  $given_name                       1 non-null      object
dtypes: float64(5), object(13)
memory usage: 17.8+ KB

In [8]:
business_map.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   variable  88 non-null     object
 1   ques_ne   88 non-null     object
 2   ques_en   88 non-null     object
dtypes: object(3)
memory usage: 2.2+ KB

In [25]:
business_map.to_excel('variable_title_mapping_businesses.xlsx', index=False)

In [251]:
business_map =  pd.read_csv('./data/variable_title_mapping_businesses_prioritised.csv')

In [252]:
business_map[:10]

                           variable                                                                               ques_ne                                                                                          ques_en  selected     input_type   group                            asked_condition
0              i_econ_stop_business                   के तपाईंले कोभिड-१९ महामारीको कारण आफ्नो व्यवसाय बन्द गर्नु पर्यो ?                                     Did you have to stop your business due to COVID-19 pandemic?         1  single-select  impact                                    general
1      i_econ_stop_business_how_lng                                 कति समय सम्म तपाईंले आफ्नो व्यापार बन्द गर्नु पर्यो ?                                                 For how long did you have to stop your business?         1  single-select  impact               business temporarily stopped
2           i_covid_effect_business              महामारीको क्रममा यी मध्ये कुन कारकले तपाईको व्यवसाय अपरेसनलाई असर गर्यो?            Which of the following factors affected your business operations during the pandemic?         1   multi-select  impact                                    general
3     i_covid_effect_business_other                                                                      अन्य खुलाउनुहोस्                                                                                    Specify other         0           text  impact       other factors that affected business
4      i_covid_effect_business_rnk1              तलका मध्ये कुन कुन कारकले तपाईको व्यवसायलाई सब भन्दा बढी प्रभावित गर्यो?                               Among the following, which factor affected your business the most?         0        ordinal  impact    more than one factors affected business
5      i_covid_effect_business_rnk2              तलका मध्ये कुन कुन कारकले तपाईको व्यवसायलाई सब भन्दा बढी प्रभावित गर्यो?                               Among the following, which factor affected your business the most?         0        ordinal  impact    more than two factors affected business
6      i_covid_effect_business_rnk3              तलका मध्ये कुन कुन कारकले तपाईको व्यवसायलाई सब भन्दा बढी प्रभावित गर्यो?                               Among the following, which factor affected your business the most?         0        ordinal  impact  more than three factors affected business
7        i_wrkfrc_actn_during_covid   महामारीको कारणले तलका मध्ये कुन कार्यबल सम्बन्धित कार्य तपाईंको व्यापारले गरेको छ ?     Which of the following workforce-related actions did your business take due to the pandemic?         1   multi-select  impact                                    general
8  i_wrkfrc_actn_during_covid_other                                        तपाईंको व्यवसाय ले अरु कुन कार्य (हरू) गर्यो ?                                                     What other action(s) did your business take?         0           text  impact                other actions business take
9         i_fin_effect_loan_avlblty  तलको कुन ऋण सम्बन्धित प्रभावहरू तपाईंको व्यवसायलाई महामारीको कारण सामना गर्नुपर्‍यो?  Which of the following loan related impacts did your business have to face due to the pandemic?         1   multi-select  impact                                    general

In [32]:
selected_questions = business_map[business_map['selected']==1]
selected_questions.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36 entries, 0 to 69
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   variable         36 non-null     object
 1   ques_ne          36 non-null     object
 2   ques_en          36 non-null     object
 3   selected         36 non-null     int64
 4   group            36 non-null     object
 5   asked_condition  36 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.0+ KB

In [36]:
for i in ['impact', 'preparedness', 'need', 'outlook']:
    print(i, (len(selected_questions[selected_questions['group']==i])))

impact 12
preparedness 5
need 12
outlook 7

In [37]:
selected_questions.to_excel('./data/variable_title_mapping_businesses_selected.xlsx', index=False)

In [71]:
import psycopg2
from sqlalchemy import create_engine

In [72]:
engine = create_engine('postgresql+psycopg2://{user}:{passwd}@{host}:{port}/{db}'.format(
        user='postgres',
        passwd=12345,
        host='localhost',
        port='5432',
        db='c2m2'))

In [28]:
business_univariate = pd.read_sql('businesses_univariate_stats', engine)

In [31]:
len(business_univariate['variable'].unique())

45

In [44]:
business_univariate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   variable        322 non-null    object
 1   value           322 non-null    object
 2   total           322 non-null    float64
 3   perc_of_total   322 non-null    object
 4   label_en        308 non-null    object
 5   label_ne        308 non-null    object
 6   choice_code     308 non-null    object
 7   variable_group  308 non-null    object
dtypes: float64(1), object(7)
memory usage: 20.2+ KB

In [49]:
selected_variables = list(selected_questions['variable'])

In [55]:
x=[]
for i in selected_variables:
    if len(x)==0:
        x = business_univariate[business_univariate['variable']==i]
        x1 = x.copy()
    else:
        x1 = pd.concat((x1,x), axis=0)

In [56]:
x1

                variable value  total perc_of_total                             label_en                                 label_ne choice_code variable_group
0   i_econ_stop_business     1    6.0     0.0555556   No, operations were always running        होइन, अपरेशनहरू सँधै चलिरहेका थिए           1         Impact
1   i_econ_stop_business     2   84.0     0.7777778  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो           2         Impact
2   i_econ_stop_business     3   18.0     0.1666667             Yes, permanently stopped                  हो, स्थायी रूपमा रोकियो           3         Impact
0   i_econ_stop_business     1    6.0     0.0555556   No, operations were always running        होइन, अपरेशनहरू सँधै चलिरहेका थिए           1         Impact
1   i_econ_stop_business     2   84.0     0.7777778  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो           2         Impact
..                   ...   ...    ...           ...                                  ...                                      ...         ...            ...
1   i_econ_stop_business     2   84.0     0.7777778  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो           2         Impact
2   i_econ_stop_business     3   18.0     0.1666667             Yes, permanently stopped                  हो, स्थायी रूपमा रोकियो           3         Impact
0   i_econ_stop_business     1    6.0     0.0555556   No, operations were always running        होइन, अपरेशनहरू सँधै चलिरहेका थिए           1         Impact
1   i_econ_stop_business     2   84.0     0.7777778  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो           2         Impact
2   i_econ_stop_business     3   18.0     0.1666667             Yes, permanently stopped                  हो, स्थायी रूपमा रोकियो           3         Impact

[108 rows x 8 columns]

In [233]:
business_data = pd.read_excel('./data/COVID-19_and_Tourism_Businesses_-_A_survey_for_assessing_COVID_impact_your_current_needs_and_future_plans_-_all_versions_-_False_-_2021-05-20-06-45-47.xlsx')

In [234]:
no_need_columns = ['m_today', 'm_start', 'm_end', 'm_username', 'm_deviceid', 'm_subscriberid', 'm_imei', 'm_phonenumber', 
                   '_span_style_color_FF_finances_and_HR_span','note_3', '_validation_status', '_submitted_by', '_tags',
                   '__version__', '_id', '_uuid', '_submission_time', '_notes', '_status','_index', 'm_biz_unn_membrshps__1',
                   'm_biz_unn_membrshps__2', 'm_biz_unn_membrshps__3', 'm_biz_unn_membrshps__4', 'm_biz_unn_membrshps__5',
                   'm_biz_unn_membrshps__6', 'm_biz_unn_membrshps__7', 'm_biz_unn_membrshps__8', 'm_biz_unn_membrshps_other',
                   'm_res_name', 'm_res_designation', 'm_res_mobile', 'm_res_email', 'm_res_biz_phone', 'm_res_biz_email',
                   '_m_coodinates_longitude', '_m_coodinates_altitude', '_m_coodinates_precision', '_m_coodinates_latitude',
                   'm_street', 'm_house_no', 'm_name_business'
                  ]

In [235]:
business_data.drop(no_need_columns, axis=1, inplace =True)

In [236]:
null_count = pd.DataFrame(business_data.isna().sum()/len(business_data) * 100).reset_index()
null_count.columns = ['variable', 'null_percentage']
null_count.head()

                       variable  null_percentage
0          i_econ_stop_business         0.000000
1  i_econ_stop_business_how_lng        22.727273
2    i_covid_effect_business__1         0.000000
3    i_covid_effect_business__2         0.000000
4    i_covid_effect_business__3         0.000000

In [237]:
# business_data.drop(null_count[null_count['null_percentage']> 90]['variable'], axis=1, inplace=True)

In [238]:
business_data.head()

   i_econ_stop_business  i_econ_stop_business_how_lng  i_covid_effect_business__1  i_covid_effect_business__2  i_covid_effect_business__3  i_covid_effect_business__4  i_covid_effect_business__5  i_covid_effect_business__6  i_covid_effect_business__7  i_covid_effect_business__8  ...  o_perm_stop_biz_new_job_sector__18  o_perm_stop_biz_new_job_sector_other  m_dist_business m_mun_business  m_mun_business_other  m_ward             m_coodinates  m_biz_type  m_biz_type_other  m_biz_years_in_operation
0                     2                           4.0                           0                           0                           0                           0                           0                           1                           1                           0  ...                                 NaN                                   NaN               35         3505.0                   NaN      12                      NaN           6               NaN                         2
1                     3                           NaN                           0                           1                           0                           0                           0                           0                           1                           0  ...                                 NaN                                   NaN               35         3501.0                   NaN      26  27.717195 85.310293 0 0           8               NaN                         4
2                     3                           NaN                           1                           0                           0                           0                           0                           0                           0                           0  ...                                 NaN                                   NaN               35         3501.0                   NaN      26  27.711873 85.312743 0 0           1               NaN                         3
3                     3                           NaN                           0                           0                           0                           0                           0                           1                           1                           0  ...                                 NaN                                   NaN               35         3501.0                   NaN      26                      NaN           7               NaN                         5
4                     2                           4.0                           1                           0                           0                           0                           0                           0                           1                           0  ...                                 NaN                                   NaN               38         3801.0                   NaN      10                      NaN           1               NaN                         5

[5 rows x 268 columns]

In [231]:
columns = []
for i in business_data.columns:
    columns.append(i)

In [232]:
null_cols=[]
for i in null_count[null_count['null_percentage']> 0.8]['variable']:
    null_cols.append(i)
#     print(i)
len(null_cols)

182

In [593]:
mapping_df = pd.read_excel('./data/mapping_business.xlsx')

In [594]:
mapping_df.head()

                       variable  value  choice_code                             label_en                                 label_ne variable_group
0          i_econ_stop_business      1            1   No, operations were always running        होइन, अपरेशनहरू सँधै चलिरहेका थिए         Impact
1          i_econ_stop_business      2            2  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो         Impact
2          i_econ_stop_business      3            3             Yes, permanently stopped                  हो, स्थायी रूपमा रोकियो         Impact
3  i_econ_stop_business_how_lng      1            4                    Less than a month                        एक महिना भन्दा कम         Impact
4  i_econ_stop_business_how_lng      2            5                        1 to 3 months                                १-३ महिना         Impact

In [595]:
business_map = business_map[business_map['group'] != 'general']

In [596]:
single_select_columns = set(business_map[business_map['input_type']=='single-select']['variable'])

In [597]:
selected_single_select = single_select_columns.intersection(set(business_data.columns))

In [598]:
single_select_df = business_data[list(selected_single_select)]

In [599]:
mapping_df['total'] = 0
mapping_df['perc_of_total'] = 0
# mapping_df['asked_condition'] = None
mapping_df['asked_total'] = 0
mapping_df['universe'] = business_data.shape[0]

In [600]:
mapping_df.head()

                       variable  value  choice_code                             label_en                                 label_ne variable_group  total  perc_of_total  asked_total  universe
0          i_econ_stop_business      1            1   No, operations were always running        होइन, अपरेशनहरू सँधै चलिरहेका थिए         Impact      0              0            0       110
1          i_econ_stop_business      2            2  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो         Impact      0              0            0       110
2          i_econ_stop_business      3            3             Yes, permanently stopped                  हो, स्थायी रूपमा रोकियो         Impact      0              0            0       110
3  i_econ_stop_business_how_lng      1            4                    Less than a month                        एक महिना भन्दा कम         Impact      0              0            0       110
4  i_econ_stop_business_how_lng      2            5                        1 to 3 months                                १-३ महिना         Impact      0              0            0       110

In [601]:
single_select_df = mapping_df.set_index('variable').transpose()[list(selected_single_select)]

In [602]:
single_select_df = single_select_df.transpose().reset_index()

In [604]:
single_select_df.head(7)

                         variable value choice_code                            label_en                           label_ne variable_group total perc_of_total asked_total universe
0  i_fin_revenue_chng_2020_v_2019     1          22           Revenue remained the same                   राजस्व उही रह्यो         Impact     0             0           0      110
1  i_fin_revenue_chng_2020_v_2019     2          23          Revenue became 75% of 2019            राजस्व २०१९ को ७५% भयो          Impact     0             0           0      110
2  i_fin_revenue_chng_2020_v_2019     3          24          Revenue became 50% of 2019            राजस्व २०१९ को ५०% भयो          Impact     0             0           0      110
3  i_fin_revenue_chng_2020_v_2019     4          25          Revenue became 25% of 2019            राजस्व २०१९ को २५% भयो          Impact     0             0           0      110
4  i_fin_revenue_chng_2020_v_2019     5          26          Revenue stopped completely          राजस्व पूर्ण रूपमा रोकियो         Impact     0             0           0      110
5  i_fin_revenue_chng_2020_v_2019     6          27  Revenue increased compared to 2019       राजस्व २०१९ को तुलनामा बढ्यो         Impact     0             0           0      110
6            i_econ_stop_business     1           1  No, operations were always running  होइन, अपरेशनहरू सँधै चलिरहेका थिए         Impact     0             0           0      110

In [605]:
single_select_dict = {}
for i in set(single_select_df['variable']):
    single_select_dict[i] = list(pd.DataFrame(business_data[i].value_counts()).reset_index().astype(int).set_index('index').to_dict().values())[0]
single_select_dict

{'i_fin_revenue_chng_2020_v_2019': {5: 70, 4: 24, 3: 8, 2: 7, 1: 1},
 'i_econ_stop_business': {2: 85, 3: 19, 1: 6},
 'i_fin_savings_chng_2020_v_2019': {6: 95, 4: 5, 5: 5, 2: 3, 3: 2},
 'i_fin_effect_other': {1: 58, 2: 52},
 'o_econ_impact_revenue_chng_21_v_19': {1: 40, 2: 25, 3: 10, 4: 6, 5: 5, 6: 5},
 'n_rcvry_preferred_loan_pybck_incntv': {1: 36, 2: 25},
 'o_econ_impact_wrkfrc_chng_21_v_19': {2: 32, 1: 29, 3: 15, 5: 7, 4: 6, 6: 2},
 'o_perm_stop_biz_future_retrn_trsm_biz': {1: 15, 2: 1},
 'o_do_u_know_of_gov_schemes': {1: 49, 2: 34, 3: 8},
 'i_wrkfrc_size_chng_2020_v_2019': {5: 40, 4: 32, 3: 15, 2: 11, 1: 10, 6: 2},
 'p_dedictd_covid_desk': {1: 65, 2: 26},
 'i_econ_stop_business_how_lng': {5: 43, 4: 24, 3: 11, 2: 5, 1: 2},
 'o_perm_stop_biz_start_new_job': {1: 17, 3: 2},
 'n_rcvry_preferred_fin_source': {1: 23, 3: 7, 2: 2, 5: 1},
 'n_rcvry_preferred_labor_asstnc': {3: 12, 1: 11, 2: 2},
 'n_rcvry_preferred_outreach_other': {1: 23, 2: 21, 3: 16},
 'n_rcvry_preferred_tax_asstn_other': {2: 43, 1: 20},
 'o_covid_how_long_it_last': {2: 48, 3: 27, 1: 23, 4: 12},
 'b_n_emplyes_pre_covid': {1: 57, 2: 38, 3: 10, 4: 3, 5: 2},
 'n_rcvry_preferred_fund_aprvl_incntv': {2: 21, 1: 12},
 'n_rcvry_preferred_tax_asstnc': {1: 20, 4: 15, 2: 6, 5: 6, 3: 3},
 'o_rcvry_biggest_support': {1: 40,
  2: 13,
  7: 13,
  4: 13,
  5: 5,
  8: 4,
  6: 2,
  3: 1}}

In [606]:
mapping_df.head()

                       variable  value  choice_code                             label_en                                 label_ne variable_group  total  perc_of_total  asked_total  universe
0          i_econ_stop_business      1            1   No, operations were always running        होइन, अपरेशनहरू सँधै चलिरहेका थिए         Impact      0              0            0       110
1          i_econ_stop_business      2            2  Yes, temporarily stopped operations  हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो         Impact      0              0            0       110
2          i_econ_stop_business      3            3             Yes, permanently stopped                  हो, स्थायी रूपमा रोकियो         Impact      0              0            0       110
3  i_econ_stop_business_how_lng      1            4                    Less than a month                        एक महिना भन्दा कम         Impact      0              0            0       110
4  i_econ_stop_business_how_lng      2            5                        1 to 3 months                                १-३ महिना         Impact      0              0            0       110

In [607]:
def variable_value(variable, value):
    var_val = []
    for idx, var in enumerate(list(variable)):
        var_val.append(var+'__' + str(list(value)[idx]))
    return var_val

In [608]:
single_select_df['variable_label'] = variable_value(single_select_df['variable'], single_select_df['value'])

In [609]:
def calc_total(variable_label):
    for i in variable_label:
        variable = i.split('__')[0]
        value = int(i.split('__')[1])
        try:
            total = single_select_dict[variable][value]
        except:
            total = 0
        asked_total = sum(list(single_select_dict[variable].values()))
        perc_of_total = total / asked_total
        single_select_df.loc[single_select_df.variable_label == i, ['total', 'perc_of_total', 'asked_total']] = total, perc_of_total, asked_total

In [610]:
calc_total(list(single_select_df['variable_label']))

In [622]:
# single_select_df.loc[mapping_df.variable=='i_fin_savings_chng_2020_v_2019']
single_select_df.head(6)

                         variable value choice_code                            label_en                      label_ne variable_group total perc_of_total asked_total universe                     variable_label
0  i_fin_revenue_chng_2020_v_2019     1          22           Revenue remained the same              राजस्व उही रह्यो         Impact     1      0.009091         110      110  i_fin_revenue_chng_2020_v_2019__1
1  i_fin_revenue_chng_2020_v_2019     2          23          Revenue became 75% of 2019       राजस्व २०१९ को ७५% भयो          Impact     7      0.063636         110      110  i_fin_revenue_chng_2020_v_2019__2
2  i_fin_revenue_chng_2020_v_2019     3          24          Revenue became 50% of 2019       राजस्व २०१९ को ५०% भयो          Impact     8      0.072727         110      110  i_fin_revenue_chng_2020_v_2019__3
3  i_fin_revenue_chng_2020_v_2019     4          25          Revenue became 25% of 2019       राजस्व २०१९ को २५% भयो          Impact    24      0.218182         110      110  i_fin_revenue_chng_2020_v_2019__4
4  i_fin_revenue_chng_2020_v_2019     5          26          Revenue stopped completely     राजस्व पूर्ण रूपमा रोकियो         Impact    70      0.636364         110      110  i_fin_revenue_chng_2020_v_2019__5
5  i_fin_revenue_chng_2020_v_2019     6          27  Revenue increased compared to 2019  राजस्व २०१९ को तुलनामा बढ्यो         Impact     0           0.0         110      110  i_fin_revenue_chng_2020_v_2019__6

In [625]:
single_select_df.loc[single_select_df.variable=='i_econ_stop_business_how_lng']

                        variable value choice_code           label_en           label_ne variable_group total perc_of_total asked_total universe                   variable_label
45  i_econ_stop_business_how_lng     1           4  Less than a month  एक महिना भन्दा कम         Impact     2      0.023529          85      110  i_econ_stop_business_how_lng__1
46  i_econ_stop_business_how_lng     2           5      1 to 3 months          १-३ महिना         Impact     5      0.058824          85      110  i_econ_stop_business_how_lng__2
47  i_econ_stop_business_how_lng     3           6      4 to 6 months          ४-६ महिना         Impact    11      0.129412          85      110  i_econ_stop_business_how_lng__3
48  i_econ_stop_business_how_lng     4           7     7 to 12 months         ७-१२ महिना         Impact    24      0.282353          85      110  i_econ_stop_business_how_lng__4
49  i_econ_stop_business_how_lng     5           8         12+ months          १२+ महिना         Impact    43      0.505882          85      110  i_econ_stop_business_how_lng__5

# Multiselect

In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', None)
import seaborn as sns

In [4]:
business_map =  pd.read_csv('./data/variable_title_mapping_businesses_prioritised.csv')
business_data = pd.read_excel('./data/business_data.xlsx')
mapping_df = pd.read_excel('./data/mapping_business.xlsx')

In [5]:
mapping_df['total'] = 0
mapping_df['perc_of_total'] = 0
mapping_df['asked_condition'] = None
mapping_df['asked_total'] = 0
mapping_df['universe'] = business_data.shape[0]

In [6]:
business_map = business_map[business_map['group'] != 'general']
business_map.head()

,variable,ques_ne,ques_en,selected,input_type,group,asked_condition
0,i_econ_stop_business,के तपाईंले कोभिड-१९ महामारीको कारण आफ्नो व्यवसाय बन्द गर्नु पर्यो ?,Did you have to stop your business due to COVID-19 pandemic?,1,single-select,impact,general
1,i_econ_stop_business_how_lng,कति समय सम्म तपाईंले आफ्नो व्यापार बन्द गर्नु पर्यो ?,For how long did you have to stop your business?,1,single-select,impact,business temporarily stopped
2,i_covid_effect_business,महामारीको क्रममा यी मध्ये कुन कारकले तपाईको व्यवसाय अपरेसनलाई असर गर्यो?,Which of the following factors affected your business operations during the pandemic?,1,multi-select,impact,general
3,i_covid_effect_business_other,अन्य खुलाउनुहोस्,Specify other,0,text,impact,other factors that affected business
4,i_covid_effect_business_rnk1,तलका मध्ये कुन कुन कारकले तपाईको व्यवसायलाई सब भन्दा बढी प्रभावित गर्यो?,"Among the following, which factor affected your business the most?",0,ordinal,impact,more than one factors affected business

In [7]:
def variable_value(variable, value):
    var_val = []
    for idx, var in enumerate(list(variable)):
        var_val.append(var+'__' + str(list(value)[idx]))
    return var_val

In [8]:
mapping_df['variable_label'] = variable_value(mapping_df['variable'], mapping_df['value'])

In [9]:
multiselect_columns = business_map[business_map['input_type'] == 'multi-select']['variable']

In [10]:
multiselect_columns = set(mapping_df['variable']).intersection(set(multiselect_columns))

In [11]:
multi_select_df = mapping_df.set_index('variable').transpose()[list(multiselect_columns)]
multi_select_df = multi_select_df.transpose().reset_index()

In [12]:
multi_select_df.head()

,variable,value,choice_code,label_en,label_ne,variable_group,total,perc_of_total,asked_condition,asked_total,universe,variable_label
0,n_rcvry_preferred_gov_policy,1,193,"Establishment of an authentic source of information for government’s COVID-related communications (e.g. health advisories, directives, etc.)","सरकारको कोभिड-१९ सम्बन्धित संचार (उदाहरण: स्वास्थ्य सल्लाहकार, निर्देशन, आदि) को लागि जानकारीको एक प्रामाणिक स्रोतको स्थापना",Need,0,0,None,0,110,n_rcvry_preferred_gov_policy__1
1,n_rcvry_preferred_gov_policy,2,194,"Regulation of port of entries such as borders, airports","प्रविष्टिहरूको पोर्ट नियमन जस्तै सीमा, एयरपोर्टहरू",Need,0,0,None,0,110,n_rcvry_preferred_gov_policy__2
2,n_rcvry_preferred_gov_policy,3,195,Establishment of government’s tourism protection fund,सरकारको पर्यटन संरक्षण कोष को स्थापना,Need,0,0,None,0,110,n_rcvry_preferred_gov_policy__3
3,n_rcvry_preferred_gov_policy,4,196,Establishment of job retention fund,रोजगारी अवधारणा कोषको स्थापना,Need,0,0,None,0,110,n_rcvry_preferred_gov_policy__4
4,n_rcvry_preferred_gov_policy,5,197,"Provision of financial assistance (e.g. no-collateral loans, subsidized loans, etc.)","वित्तीय सहायताको प्रावधान (उदाहरणका लागि कुनै पनि जमानत ऋण, सरकारी ऋण, आदि)",Need,0,0,None,0,110,n_rcvry_preferred_gov_policy__5

In [13]:
def calc_total_multiselect(variable_label):
    for i in variable_label:
        multi_select_df.loc[multi_select_df.variable_label == i, ['total']] = business_data[i].sum()

In [14]:
calc_total_multiselect(list(multi_select_df['variable_label']))

In [15]:
multi_select_df.head()

,variable,value,choice_code,label_en,label_ne,variable_group,total,perc_of_total,asked_condition,asked_total,universe,variable_label
0,n_rcvry_preferred_gov_policy,1,193,"Establishment of an authentic source of information for government’s COVID-related communications (e.g. health advisories, directives, etc.)","सरकारको कोभिड-१९ सम्बन्धित संचार (उदाहरण: स्वास्थ्य सल्लाहकार, निर्देशन, आदि) को लागि जानकारीको एक प्रामाणिक स्रोतको स्थापना",Need,23.0,0,None,0,110,n_rcvry_preferred_gov_policy__1
1,n_rcvry_preferred_gov_policy,2,194,"Regulation of port of entries such as borders, airports","प्रविष्टिहरूको पोर्ट नियमन जस्तै सीमा, एयरपोर्टहरू",Need,39.0,0,None,0,110,n_rcvry_preferred_gov_policy__2
2,n_rcvry_preferred_gov_policy,3,195,Establishment of government’s tourism protection fund,सरकारको पर्यटन संरक्षण कोष को स्थापना,Need,60.0,0,None,0,110,n_rcvry_preferred_gov_policy__3
3,n_rcvry_preferred_gov_policy,4,196,Establishment of job retention fund,रोजगारी अवधारणा कोषको स्थापना,Need,12.0,0,None,0,110,n_rcvry_preferred_gov_policy__4
4,n_rcvry_preferred_gov_policy,5,197,"Provision of financial assistance (e.g. no-collateral loans, subsidized loans, etc.)","वित्तीय सहायताको प्रावधान (उदाहरणका लागि कुनै पनि जमानत ऋण, सरकारी ऋण, आदि)",Need,47.0,0,None,0,110,n_rcvry_preferred_gov_policy__5

In [16]:
multi_select_df.loc[multi_select_df['label_en'] == 'Savings became 25% of 2019', 'total'] = sum(multi_select_df.loc[multi_select_df['label_en'] == 'Savings became 25% of 2019']['total'])

In [17]:
# count_dict = {}
# for i in multi_select_df['variable']:
#     main_count = 0
#     for j in range(len(business_data)):
#         if i in business_data.iloc[j]
#         print(i, business_data.iloc[j][i])
# #     main_count = 0 
# #     for j in range(len(business_data)):
# #         if business_data.iloc[j][i] == 1:
# #             main_count += 1
#     count_dict[i.split('__')[0]] = main_count

In [18]:
# count_dict

In [19]:
label_dict = {}
for i in multi_select_df['variable']:
    label_dict[i] = list(multi_select_df[multi_select_df['variable']==i]['variable_label'])

In [20]:
count_dict = {}
for i in label_dict.keys():
    count = 0
    for j in business_data[label_dict[i]].values:
        if 1 in j:
            count +=1
    count_dict[i] = count

In [21]:
multi_select_df['asked_total'] = multi_select_df['variable'].apply(lambda x: count_dict[x])
multi_select_df['perc_of_total'] = multi_select_df['total'] / multi_select_df['asked_total']
# multi_select_df['total'] = multi_select_df['total'].astype(int)

In [22]:
# count_dict

In [23]:
# count = 0
# for i in business_data[label_dict['p_hlth_safety_measures']].values:
# #     print(i)
#     if 1 in i:
#         count +=1
#     print(i, count)

In [24]:
# multi_select_df[multi_select_df['variable'] == 'p_hlth_safety_measures']

# Prepare Univariate data generation script

In [73]:
import numpy as np
import pandas as pd
pd.set_option('display.max_colwidth', None)
# import seaborn as sns
# import matplotlib.pyplot as plt

In [74]:
import psycopg2
from sqlalchemy import create_engine

In [75]:
engine = create_engine('postgresql+psycopg2://{user}:{passwd}@{host}:{port}/{db}'.format(
        user='postgres',
        passwd=12345,
        host='localhost',
        port='5432',
        db='c2m2'))

In [76]:
business_map =  pd.read_excel('./data/variable_title_mapping_businesses_prioritized.xlsx')
business_data = pd.read_excel('./data/business_data.xlsx')
mapping_df = pd.read_excel('./data/mapping_business_updated.xlsx')
selected_variables = business_map[business_map['selected'] ==1]
# business_variable_map =  pd.read_excel('./data/variable_title_mapping_businesses_prioritized.xlsx')
# business_raw_data = pd.read_excel('./data/business_data.xlsx')
# business_labels_map = pd.read_excel('./data/mapping_business_updated.xlsx')

In [77]:
mapping_df['total'] = 0
mapping_df['perc_of_total'] = 0
# mapping_df['asked_condition'] = None
mapping_df['asked_total'] = 0
mapping_df['universe'] = business_data.shape[0]

In [78]:
business_map = business_map[business_map['group'] != 'general']

In [79]:
def variable_value(variable, value):
    var_val = []
    for idx, var in enumerate(list(variable)):
        var_val.append(var+'__' + str(list(value)[idx]))
    return var_val

In [80]:
mapping_df['variable_label'] = variable_value(mapping_df['variable'], mapping_df['value'])

In [81]:
single_select_columns = set(selected_variables[selected_variables['input_type']=='single-select']['variable'])
single_select_columns = single_select_columns.intersection(set(business_data.columns))
single_select_df = mapping_df.set_index('variable').transpose()[list(single_select_columns)]
single_select_df = single_select_df.transpose().reset_index()

In [82]:
single_select_df

,variable,value,choice_code,label_en,label_ne,variable_group,total,perc_of_total,asked_total,universe,variable_label
0,n_rcvry_preferred_labor_asstnc,1,54,Government provision to not increase minimum wages for the next some time,पछिल्लो समय न्यूनतम ज्याला नबढाउने सरकारी प्रावधान,Need,0,0,0,110,n_rcvry_preferred_labor_asstnc__1
1,n_rcvry_preferred_labor_asstnc,2,55,Increased access to skilled/semi-skilled workers,दक्ष / अर्ध-कुशल कामदारहरूको पहुँच बढाउने,Need,0,0,0,110,n_rcvry_preferred_labor_asstnc__2
2,n_rcvry_preferred_labor_asstnc,3,56,Prioritized provision of COVID-19 vaccination to my workers/employees,कामदारहरू / कर्मचारीहरूलाई कोभिड-१९ खोपको प्राथमिकतामा प्रावधान,Need,0,0,0,110,n_rcvry_preferred_labor_asstnc__3
3,i_wrkfrc_size_chng_2020_v_2019,1,16,Workforce size remained the same,कार्यबल आकार उही रह्यो,Impact,0,0,0,110,i_wrkfrc_size_chng_2020_v_2019__1
4,i_wrkfrc_size_chng_2020_v_2019,2,17,Workforce size became 75% of 2019,कार्यबल आकार २०१९ को ७५% भयो,Impact,0,0,0,110,i_wrkfrc_size_chng_2020_v_2019__2
...,...,...,...,...,...,...,...,...,...,...,...
80,o_econ_impact_wrkfrc_chng_21_v_19,2,74,Workforce size will be 25% of 2019,कार्यबल आकार २०१९ को २५% हुनेछ,Outlook,0,0,0,110,o_econ_impact_wrkfrc_chng_21_v_19__2
81,o_econ_impact_wrkfrc_chng_21_v_19,3,75,Workforce size will be 50% of 2019,कार्यबल आकार २०१९ को ५०% हुनेछ,Outlook,0,0,0,110,o_econ_impact_wrkfrc_chng_21_v_19__3
82,o_econ_impact_wrkfrc_chng_21_v_19,4,76,Workforce size will be 75% of 2019,कार्यबल आकार २०१९ को ७५% हुनेछ,Outlook,0,0,0,110,o_econ_impact_wrkfrc_chng_21_v_19__4
83,o_econ_impact_wrkfrc_chng_21_v_19,5,77,Workforce size will be similar to that of 2019,कार्यबल आकार २०१९ को जस्तै मिल्दो हुनेछ,Outlook,0,0,0,110,o_econ_impact_wrkfrc_chng_21_v_19__5
84,o_econ_impact_wrkfrc_chng_21_v_19,6,78,Workforce size will be greater than that of 2019,कार्यबल आकार २०१९ को भन्दा बढी हुनेछ,Outlook,0,0,0,110,o_econ_impact_wrkfrc_chng_21_v_19__6

In [87]:
single_select_dict = {}
for i in set(single_select_df['variable']):
    single_select_dict[i] = list(pd.DataFrame(business_data[i].value_counts()).reset_index().astype(int).set_index('index').to_dict().values())[0]

In [88]:
def calc_total_singleselect(variable_label):
    for i in variable_label:
        variable = i.split('__')[0]
        value = int(i.split('__')[1])
        try:
            total = single_select_dict[variable][value]
        except:
            total = 0
        asked_total = sum(list(single_select_dict[variable].values()))
        single_select_df.loc[single_select_df.variable_label == i, ['total', 'asked_total']] = total, asked_total

In [89]:
calc_total_singleselect(list(single_select_df['variable_label']))

In [90]:
single_select_df.loc[single_select_df['label_en'] == 'Savings became 25% of 2019', 'total'] = sum(single_select_df.loc[single_select_df['label_en'] == 'Savings became 25% of 2019']['total'])

In [91]:
single_select_df['perc_of_total'] = single_select_df['total'] / single_select_df['asked_total']

In [92]:
single_select_df.drop(single_select_df.loc[single_select_df['label_en'] == 'Savings became 25% of 2019'][1:].index[0], axis=0, inplace=True)

In [93]:
single_select_df

,variable,value,choice_code,label_en,label_ne,variable_group,total,perc_of_total,asked_total,universe,variable_label
0,n_rcvry_preferred_labor_asstnc,1,54,Government provision to not increase minimum wages for the next some time,पछिल्लो समय न्यूनतम ज्याला नबढाउने सरकारी प्रावधान,Need,11,0.44,25,110,n_rcvry_preferred_labor_asstnc__1
1,n_rcvry_preferred_labor_asstnc,2,55,Increased access to skilled/semi-skilled workers,दक्ष / अर्ध-कुशल कामदारहरूको पहुँच बढाउने,Need,2,0.08,25,110,n_rcvry_preferred_labor_asstnc__2
2,n_rcvry_preferred_labor_asstnc,3,56,Prioritized provision of COVID-19 vaccination to my workers/employees,कामदारहरू / कर्मचारीहरूलाई कोभिड-१९ खोपको प्राथमिकतामा प्रावधान,Need,12,0.48,25,110,n_rcvry_preferred_labor_asstnc__3
3,i_wrkfrc_size_chng_2020_v_2019,1,16,Workforce size remained the same,कार्यबल आकार उही रह्यो,Impact,10,0.090909,110,110,i_wrkfrc_size_chng_2020_v_2019__1
4,i_wrkfrc_size_chng_2020_v_2019,2,17,Workforce size became 75% of 2019,कार्यबल आकार २०१९ को ७५% भयो,Impact,11,0.1,110,110,i_wrkfrc_size_chng_2020_v_2019__2
...,...,...,...,...,...,...,...,...,...,...,...
80,o_econ_impact_wrkfrc_chng_21_v_19,2,74,Workforce size will be 25% of 2019,कार्यबल आकार २०१९ को २५% हुनेछ,Outlook,32,0.351648,91,110,o_econ_impact_wrkfrc_chng_21_v_19__2
81,o_econ_impact_wrkfrc_chng_21_v_19,3,75,Workforce size will be 50% of 2019,कार्यबल आकार २०१९ को ५०% हुनेछ,Outlook,15,0.164835,91,110,o_econ_impact_wrkfrc_chng_21_v_19__3
82,o_econ_impact_wrkfrc_chng_21_v_19,4,76,Workforce size will be 75% of 2019,कार्यबल आकार २०१९ को ७५% हुनेछ,Outlook,6,0.065934,91,110,o_econ_impact_wrkfrc_chng_21_v_19__4
83,o_econ_impact_wrkfrc_chng_21_v_19,5,77,Workforce size will be similar to that of 2019,कार्यबल आकार २०१९ को जस्तै मिल्दो हुनेछ,Outlook,7,0.076923,91,110,o_econ_impact_wrkfrc_chng_21_v_19__5
84,o_econ_impact_wrkfrc_chng_21_v_19,6,78,Workforce size will be greater than that of 2019,कार्यबल आकार २०१९ को भन्दा बढी हुनेछ,Outlook,2,0.021978,91,110,o_econ_impact_wrkfrc_chng_21_v_19__6

In [94]:
multiselect_columns = selected_variables[selected_variables['input_type'] == 'multi-select']['variable']
multiselect_columns = set(mapping_df['variable']).intersection(set(multiselect_columns))
multi_select_df = mapping_df.set_index('variable').transpose()[list(multiselect_columns)]
multi_select_df = multi_select_df.transpose().reset_index()

In [95]:
def calc_total_multiselect(variable_label):
    for i in variable_label:
        multi_select_df.loc[multi_select_df['variable_label'] == i, ['total']] = business_data[i].sum()

In [96]:
calc_total_multiselect(list(multi_select_df['variable_label']))

In [97]:
label_dict = {}
for i in multi_select_df['variable']:
    label_dict[i] = list(multi_select_df[multi_select_df['variable']==i]['variable_label'])

count_dict = {}
for i in label_dict.keys():
    count = 0
    for j in business_data[label_dict[i]].values:
        if 1 in j:
            count +=1
    count_dict[i] = count

In [98]:
multi_select_df['asked_total'] = multi_select_df['variable'].apply(lambda x: count_dict[x])
multi_select_df['perc_of_total'] = multi_select_df['total'] / multi_select_df['asked_total']
multi_select_df['total'] = multi_select_df['total'].astype(int)
multi_select_df['perc_of_total'].fillna(0, inplace=True)

In [99]:
business_univariate = pd.concat([single_select_df,multi_select_df])

In [100]:
business_univariate

,variable,value,choice_code,label_en,label_ne,variable_group,total,perc_of_total,asked_total,universe,variable_label
0,n_rcvry_preferred_labor_asstnc,1,54,Government provision to not increase minimum wages for the next some time,पछिल्लो समय न्यूनतम ज्याला नबढाउने सरकारी प्रावधान,Need,11,0.44,25,110,n_rcvry_preferred_labor_asstnc__1
1,n_rcvry_preferred_labor_asstnc,2,55,Increased access to skilled/semi-skilled workers,दक्ष / अर्ध-कुशल कामदारहरूको पहुँच बढाउने,Need,2,0.08,25,110,n_rcvry_preferred_labor_asstnc__2
2,n_rcvry_preferred_labor_asstnc,3,56,Prioritized provision of COVID-19 vaccination to my workers/employees,कामदारहरू / कर्मचारीहरूलाई कोभिड-१९ खोपको प्राथमिकतामा प्रावधान,Need,12,0.48,25,110,n_rcvry_preferred_labor_asstnc__3
3,i_wrkfrc_size_chng_2020_v_2019,1,16,Workforce size remained the same,कार्यबल आकार उही रह्यो,Impact,10,0.090909,110,110,i_wrkfrc_size_chng_2020_v_2019__1
4,i_wrkfrc_size_chng_2020_v_2019,2,17,Workforce size became 75% of 2019,कार्यबल आकार २०१९ को ७५% भयो,Impact,11,0.1,110,110,i_wrkfrc_size_chng_2020_v_2019__2
...,...,...,...,...,...,...,...,...,...,...,...
112,p_recvry_strategic_actions_internl,4,310,Starting a different business,फरक व्यवसाय सुरू गर्दै,Preparedness,9,0.098901,91,110,p_recvry_strategic_actions_internl__4
113,p_recvry_strategic_actions_internl,5,311,"Diversifying its sales channels – online marketing, sales, delivery, etc.","यसको बिक्री च्यानलहरूको विविधिकरण गर्दै - अनलाइन मार्केटिंग, बिक्री, डेलिभरी, आदि।",Preparedness,19,0.208791,91,110,p_recvry_strategic_actions_internl__5
114,p_recvry_strategic_actions_internl,6,312,Re-training its workers,यसका कार्यकर्ताहरूलाई पुन: प्रशिक्षण,Preparedness,9,0.098901,91,110,p_recvry_strategic_actions_internl__6
115,p_recvry_strategic_actions_internl,7,313,Other,अन्य,Preparedness,7,0.076923,91,110,p_recvry_strategic_actions_internl__7
116,p_recvry_strategic_actions_internl,8,314,We did not have to take any action,हामीले कुनै पनि कार्य गर्नुपरेन,Preparedness,29,0.318681,91,110,p_recvry_strategic_actions_internl__8

In [31]:
business_univariate.drop('variable_label', axis=1, inplace=True)

In [23]:
questions_processed =  list(business_univariate['variable'].unique())
# multi_select_df.info()

In [24]:
# business_univariate[business_univariate['variable'] == 'i_fin_effect_other']

In [25]:
remaining_columns = set(business_map['variable'].unique()).difference(set(questions_processed))

In [26]:
# questions_processed

In [27]:
business_univariate['index'] = list(range(1, len(business_univariate)+1))
business_univariate.drop('choice_code', axis=1, inplace=True)

In [28]:
# visuallization_df = business_univariate[business_univariate['variable']== 'i_covid_effect_business']
# plt.figure(figsize=(20,6))
# sns.barplot(x='label_en', y='total', data=visuallization_df)
# plt.show()

In [29]:
business_univariate.to_sql('businesses_univariate_stats', engine, if_exists='replace')

In [30]:
business_univariate.to_excel('businesses_univariate_stats.xlsx', index=False)

In [31]:
asked_total = business_univariate[['variable', 'asked_total']].drop_duplicates(subset='variable').set_index('variable').to_dict()

In [32]:
asked_total = asked_total['asked_total']

In [14]:
# asked_total

In [34]:
def map_total(variable):
    try:
        total = asked_total[variable]
    except:
        total = 0
    return total

In [35]:
variable_title_mapping_businesses = pd.read_excel('variable_title_mapping_businesses.xlsx')
variable_title_mapping_businesses['asked_total'] = 0
variable_title_mapping_businesses['asked_total'] = variable_title_mapping_businesses['variable'].apply(lambda x: map_total(x))

In [36]:
variable_title_mapping_businesses = variable_title_mapping_businesses[['variable', 'ques_ne', 'ques_en', 'selected', 'input_type', \
                                                                       'group', 'asked_condition', 'asked_total']]

In [37]:
variable_title_mapping_businesses.to_excel('variable_title_mapping_businesses.xlsx', index=False)

In [38]:
business_univariate[business_univariate['variable'] == 'o_perm_stop_biz_start_new_job']

,variable,value,label_en,label_ne,variable_group,total,perc_of_total,asked_total,universe,index
74,o_perm_stop_biz_start_new_job,1,No,छैन,Outlook,17,0.894737,19,110,74
75,o_perm_stop_biz_start_new_job,2,"Yes, it is a tourism-related job","छु, यो एक पर्यटन सम्बन्धित काम हो",Outlook,0,0.0,19,110,75
76,o_perm_stop_biz_start_new_job,3,"Yes, but it is a non-tourism related job","छु, यो पर्यटन सम्बन्धित काम होइन",Outlook,2,0.105263,19,110,76

# Prepare Bivariate data generation script

### Data generation for single-select variable

In [46]:
group_by_columns = ['m_biz_type', 'm_biz_years_in_operation', 'b_n_emplyes_pre_covid']

In [47]:
single_select_bi_columns = [ i for i in single_select_columns if i != 'b_n_emplyes_pre_covid']

In [48]:
single_select_bivariate_columns = list(single_select_bi_columns) + group_by_columns

In [49]:
ss_bivariate_raw = business_data[single_select_bivariate_columns]

In [50]:
b_single_bivariate = []
for x_variable in group_by_columns:
    for y_variable in single_select_bi_columns:
        # create tuples all possible rows 
        value_tup = []
        for i in mapping_df[mapping_df['variable'] == x_variable].value:
            for j in mapping_df[mapping_df['variable'] == y_variable].value:
                value_tup.append((i,j))

        # create labels and value mapping for both x and y variables
        y_label_dict = mapping_df.loc[mapping_df['variable']==y_variable][['value', 'label_en', 'label_ne', 'variable_group']].set_index('value').to_dict()
        x_label_dict = mapping_df.loc[mapping_df['variable']==x_variable][['value', 'label_en', 'label_ne', 'variable_group']].set_index('value').to_dict()

        # group by x variable and calculate y variable value counts for each x variable
        i_fin = pd.DataFrame(ss_bivariate_raw.groupby([x_variable])[y_variable].value_counts())
        i_fin.columns = ['total']

        # check if any possible combination of x and y variable is missing, then add missing combination with total of 0.
        i_fin = i_fin.to_dict()
        for i in value_tup:
            if i not in i_fin['total'].keys():
                i_fin['total'][i] = 0
        i_fin = pd.DataFrame(i_fin)

        # Add additional columns like x_variable, y_variable, x_label_ne, x_label_en, etc. in the dataframe
        i_fin.reset_index(inplace=True)
        i_fin['x_variable'] = x_variable
        i_fin['y_variable'] = y_variable
        i_fin.columns = ['x_value', 'y_value', 'total', 'x_variable', 'y_variable']
        i_fin['y_label_en'] = i_fin['y_value'].apply(lambda x: y_label_dict['label_en'][x])
        i_fin['y_label_ne'] = i_fin['y_value'].apply(lambda x: y_label_dict['label_ne'][x])
        i_fin['x_label_en'] = i_fin['x_value'].apply(lambda x: x_label_dict['label_en'][x])
        i_fin['x_label_ne'] = i_fin['x_value'].apply(lambda x: x_label_dict['label_ne'][x])
        i_fin['variable_group'] = y_label_dict['variable_group'][1]
        i_fin = i_fin[['x_variable', 'x_value', 'x_label_en','x_label_ne', 'y_variable', 'y_value','y_label_en','y_label_ne', 'total', 'variable_group']]
        if len(b_single_bivariate)==0:
            b_single_bivariate = i_fin
        else:
            b_single_bivariate = pd.concat((b_single_bivariate, i_fin))

In [52]:
# for x_variable in group_by_columns:
#     for y_variable in single_select_columns:
# #         print(pd.DataFrame(ss_bivariate_raw.groupby(['b_n_emplyes_pre_covid'])['i_econ_stop_business'].value_counts()))
#         print(x_variable, y_variable)

###  Data generation for multi-select variable

In [53]:
multi_select_labels = mapping_df.set_index('variable').transpose()[list(multiselect_columns)].transpose()['variable_label'].values.tolist()
multi_select_bivariate_labels = multi_select_labels + group_by_columns

In [54]:
ms_business_raw = business_data[multi_select_bivariate_labels]

In [55]:
b_multi_bivariate = []
for x_variable in group_by_columns:
    for y_variable in multi_select_labels:
        ms_bivariate_df = pd.DataFrame(ms_business_raw.groupby(x_variable)[y_variable].sum())
        ms_bivariate_df.columns = ['total']
        ms_bivariate_df.reset_index(inplace=True)
        
        y_label_dict = mapping_df.loc[mapping_df['variable']==y_variable.split('__')[0]][['value', 'label_en', 'label_ne', 'variable_group']].set_index('value').to_dict()
        x_label_dict = mapping_df.loc[mapping_df['variable']==x_variable][['value', 'label_en', 'label_ne', 'variable_group']].set_index('value').to_dict()
        
        ms_bivariate_df['x_variable'] = x_variable
        ms_bivariate_df['y_variable'] = y_variable.split('__')[0]
        ms_bivariate_df['y_value'] = int(y_variable.split('__')[1])
        ms_bivariate_df.columns = ['x_value', 'total', 'x_variable', 'y_variable', 'y_value']
        ms_bivariate_df['y_label_en'] = ms_bivariate_df['y_value'].apply(lambda x: y_label_dict['label_en'][x])
        ms_bivariate_df['y_label_ne'] = ms_bivariate_df['y_value'].apply(lambda x: y_label_dict['label_ne'][x])
        ms_bivariate_df['x_label_en'] = ms_bivariate_df['x_value'].apply(lambda x: x_label_dict['label_en'][x])
        ms_bivariate_df['x_label_ne'] = ms_bivariate_df['x_value'].apply(lambda x: x_label_dict['label_ne'][x])
        ms_bivariate_df['variable_group'] = y_label_dict['variable_group'][1]
        ms_bivariate_df = ms_bivariate_df[['x_variable', 'x_value', 'x_label_en','x_label_ne', 'y_variable', 'y_value','y_label_en','y_label_ne', 'total', 'variable_group']]
        
        if len(b_multi_bivariate)==0:
            b_multi_bivariate = ms_bivariate_df
        else:
            b_multi_bivariate = pd.concat((b_multi_bivariate, ms_bivariate_df))

In [56]:
business_bivariate_stats = pd.concat((b_single_bivariate, b_multi_bivariate))

In [57]:
business_bivariate_stats.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5643 entries, 0 to 4
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   x_variable      5643 non-null   object
 1   x_value         5643 non-null   int64
 2   x_label_en      5643 non-null   object
 3   x_label_ne      5643 non-null   object
 4   y_variable      5643 non-null   object
 5   y_value         5643 non-null   float64
 6   y_label_en      5643 non-null   object
 7   y_label_ne      5643 non-null   object
 8   total           5643 non-null   float64
 9   variable_group  5643 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 484.9+ KB

In [149]:
# business_univariate[business_univariate['variable'] == 'i_covid_effect_business']

In [191]:
# business_uni = pd.read_sql('businesses_bivariate_stats', engine)

In [192]:
# viz_bi = business_uni.loc[business_uni['x_variable'] == 'm_biz_type']

In [193]:
# viz_bi = viz_bi[viz_bi['y_variable'] == 'i_covid_effect_business']
# viz_bi

In [203]:
business_data['m_dist_business'].unique().tolist()

[35, 38, 12, 34, 68, 30, 9, 10, 40]

In [59]:
ss_bivariate_raw['b_n_emplyes_pre_covid'].value_counts()

1    57
2    38
3    10
4     3
5     2
Name: b_n_emplyes_pre_covid, dtype: int64

# Data Prepration Script

In [67]:
import numpy as np
import pandas as pd
import psycopg2
from sqlalchemy import create_engine
pd.set_option('display.max_colwidth', None)

In [68]:
engine = create_engine('postgresql+psycopg2://{user}:{passwd}@{host}:{port}/{db}'.format(
        user='postgres',
        passwd=12345,
        host='localhost',
        port='5432',
        db='c2m2'))

In [69]:
business_variable_map =  pd.read_csv('./data/variable_title_mapping_businesses_prioritized.csv')
business_data_raw = pd.read_excel('./data/business_data.xlsx')
business_labels_map = pd.read_excel('./data/mapping_business_updated.xlsx')

In [70]:
selected_business_variables = business_variable_map[business_variable_map['selected'] ==1]
s_select_variables = selected_business_variables[selected_business_variables['input_type'] == 'single-select']['variable'].values.tolist()
m_select_variables = selected_business_variables[selected_business_variables['input_type'] == 'multi-select']['variable'].values.tolist()

In [71]:
def variable_value(variable, value):
    var_val = []
    for idx, var in enumerate(list(variable)):
        var_val.append(var+'__' + str(list(value)[idx]))
    return var_val

#### UNIVARIATE

In [72]:
business_labels_map[['total', 'perc_of_total', 'asked_total']] = 0
business_labels_map['universe'] = business_data_raw.shape[0]
business_labels_map['variable_label'] = variable_value(business_labels_map['variable'], business_labels_map['value'])

In [73]:
s_select_univariate = business_labels_map.set_index('variable').transpose()[s_select_variables]
s_select_univariate = s_select_univariate.transpose().reset_index()

In [74]:
# s_select_dict = {}
# for i in set(s_select_univariate['variable']):
#     s_select_dict[i] = list(pd.DataFrame(business_data_raw[i].value_counts()).reset_index().astype(int).set_index('index').to_dict().values())[0]
def generate_total(df):
    s_select_dict = {}
    for i in set(df['variable']):
        label_counts = pd.DataFrame(business_data_raw[i].value_counts()).reset_index()
        label_counts = label_counts.astype(int)
        label_counts = label_counts.set_index('index').to_dict().values()
        s_select_dict[i] = list(label_counts)[0]
    for i in list(df['variable_label']):
        variable = i.split('__')[0]
        value = int(i.split('__')[1])
        try:
            total = s_select_dict[variable][value]
        except:
            total = 0
        asked_total = sum(list(s_select_dict[variable].values()))
        s_select_univariate.loc[s_select_univariate.variable_label == i, ['total', 'asked_total']] = total, asked_total
#     return s_select_dict
# s_select_dict = counts_dict(s_select_univariate)

In [75]:
# def s_select_total(variable_label):
#     for i in variable_label:
#         variable = i.split('__')[0]
#         value = int(i.split('__')[1])
#         try:
#             total = s_select_dict[variable][value]
#         except:
#             total = 0
#         asked_total = sum(list(s_select_dict[variable].values()))
#         s_select_univariate.loc[s_select_univariate.variable_label == i, ['total', 'asked_total']] = total, asked_total

In [79]:
s_select_univariate

,variable,value,choice_code,label_en,label_ne,variable_group,total,perc_of_total,asked_total,universe,variable_label
0,i_econ_stop_business,1,1,"No, operations were always running","होइन, अपरेशनहरू सँधै चलिरहेका थिए",Impact,6,0.054545,110,110,i_econ_stop_business__1
1,i_econ_stop_business,2,2,"Yes, temporarily stopped operations","हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो",Impact,85,0.772727,110,110,i_econ_stop_business__2
2,i_econ_stop_business,3,3,"Yes, permanently stopped","हो, स्थायी रूपमा रोकियो",Impact,19,0.172727,110,110,i_econ_stop_business__3
3,i_econ_stop_business_how_lng,1,4,Less than a month,एक महिना भन्दा कम,Impact,2,0.023529,85,110,i_econ_stop_business_how_lng__1
4,i_econ_stop_business_how_lng,2,5,1 to 3 months,१-३ महिना,Impact,5,0.058824,85,110,i_econ_stop_business_how_lng__2
...,...,...,...,...,...,...,...,...,...,...,...
80,o_perm_stop_biz_future_retrn_trsm_biz,1,87,Yes,फर्किने छु,Outlook,15,0.9375,16,110,o_perm_stop_biz_future_retrn_trsm_biz__1
81,o_perm_stop_biz_future_retrn_trsm_biz,2,88,No,फर्किने छैन,Outlook,1,0.0625,16,110,o_perm_stop_biz_future_retrn_trsm_biz__2
82,o_perm_stop_biz_start_new_job,1,89,No,छैन,Outlook,17,0.894737,19,110,o_perm_stop_biz_start_new_job__1
83,o_perm_stop_biz_start_new_job,2,90,"Yes, it is a tourism-related job","छु, यो एक पर्यटन सम्बन्धित काम हो",Outlook,0,0.0,19,110,o_perm_stop_biz_start_new_job__2
84,o_perm_stop_biz_start_new_job,3,91,"Yes, but it is a non-tourism related job","छु, यो पर्यटन सम्बन्धित काम होइन",Outlook,2,0.105263,19,110,o_perm_stop_biz_start_new_job__3

In [76]:
generate_total(s_select_univariate)

In [77]:
s_select_univariate['perc_of_total'] = s_select_univariate['total'] / s_select_univariate['asked_total']

In [78]:
s_select_univariate.drop(s_select_univariate.loc[s_select_univariate['label_en'] == 'Savings became 25% of 2019'][1:].index[0], axis=0, inplace=True)

# CLASS SCRIPT

In [2]:
import pandas as pd
import numpy as np

In [102]:
class Univariate():
    def __init__(self, raw_data, variable_map, labels_map):
        self.raw_data = raw_data
        self.variable_map = variable_map
        self.labels_map = labels_map
        self.selected_variables = self.variable_map[self.variable_map['selected'] ==1]
        self.s_select_variables = self.selected_variables[self.selected_variables['input_type'] == 'single-select']['variable'].values.tolist()
        self.m_select_variables = self.selected_variables[self.selected_variables['input_type'] == 'multi-select']['variable'].values.tolist()
    
    def generate_univariate(self):
        univariate_stats = pd.concat([self.generate_singleselect(),self.generate_multiselect()])
        univariate_stats.drop('variable_label', axis=1, inplace=True)
        univariate_stats['index'] = list(range(1, len(univariate_stats)+1))
        univariate_stats.drop('choice_code', axis=1, inplace=True)
        return univariate_stats
    
    
    def generate_singleselect(self):
        self.initiallize_columns()
        s_select_univariate = self.labels_map.set_index('variable').transpose()[self.s_select_variables]
        s_select_univariate = s_select_univariate.transpose().reset_index()
        self.s_select_generate_total(s_select_univariate)
        self.special_cases_univariate(s_select_univariate)
        s_select_univariate['perc_of_total'] = s_select_univariate['total'] / s_select_univariate['asked_total']
        s_select_univariate['total'] = s_select_univariate['total'].astype(int)
        s_select_univariate['perc_of_total'].fillna(0, inplace=True)
        return s_select_univariate
    
    def generate_multiselect(self):
        self.initiallize_columns()
        m_select_univariate = self.labels_map.set_index('variable').transpose()[self.m_select_variables]
        m_select_univariate = m_select_univariate.transpose().reset_index()
        self.m_select_generate_total(m_select_univariate)
        m_select_univariate['perc_of_total'] = m_select_univariate['total'] / m_select_univariate['asked_total']
        m_select_univariate['total'] = m_select_univariate['total'].astype(int)
        m_select_univariate['perc_of_total'].fillna(0, inplace=True)
        return m_select_univariate    
    
    def initiallize_columns(self):
        self.labels_map[['total', 'perc_of_total', 'asked_total']] = 0
        self.labels_map['universe'] = self.raw_data.shape[0]
        self.labels_map['variable_label'] = self.variable_value(self.labels_map['variable'], self.labels_map['value'])
        
    def s_select_generate_total(self, df):
        count_dict = {}
        for i in set(df['variable']):
            label_counts = pd.DataFrame(self.raw_data[i].value_counts()).reset_index()
            label_counts = label_counts.astype(int)
            label_counts = label_counts.set_index('index').to_dict().values()
            count_dict[i] = list(label_counts)[0]
        for i in list(df['variable_label']):
            variable = i.split('__')[0]
            value = int(i.split('__')[1])
            try:
                total = count_dict[variable][value]
            except:
                total = 0
            asked_total = sum(list(count_dict[variable].values()))
            df.loc[df['variable_label'] == i, ['total', 'asked_total']] = total, asked_total
                
    def m_select_generate_total(self, df):
        label_dict = {}
        for i in df['variable']:
            label_dict[i] = list(df[df['variable']==i]['variable_label'])
        count_dict = {}
        for i in label_dict.keys():
            count = 0
            for j in self.raw_data[label_dict[i]].values:
                if 1 in j:
                    count +=1
            count_dict[i] = count
        for i in  list(df['variable_label']):
            df.loc[df['variable_label'] == i, ['total']] = self.raw_data[i].sum()
        df['asked_total'] = df['variable'].apply(lambda x: count_dict[x])
            
    def special_cases_univariate(self, df):
        fixed_total = sum(df.loc[df['label_en'] == 'Savings became 25% of 2019']['total'])
        df.loc[df['label_en'] == 'Savings became 25% of 2019', 'total'] = fixed_total
        df.drop(df.loc[df['label_en'] == 'Savings became 25% of 2019'][1:].index[0], axis=0, inplace=True)


    def variable_value(self, variable, value):
        var_val = []
        for idx, var in enumerate(list(variable)):
            var_val.append(var+'__' + str(list(value)[idx]))
        return var_val

In [103]:
business_variable_map =  pd.read_excel('./data/variable_title_mapping_businesses_prioritized.xlsx')
business_raw_data = pd.read_excel('./data/business_data.xlsx')
business_labels_map = pd.read_excel('./data/mapping_business_updated.xlsx')
business_univariate = Univariate(raw_data=business_raw_data, variable_map=business_variable_map, labels_map=business_labels_map)

In [104]:
business_univariate.generate_univariate().head()

,variable,value,label_en,label_ne,variable_group,total,perc_of_total,asked_total,universe,index
0,i_econ_stop_business,1,"No, operations were always running","होइन, अपरेशनहरू सँधै चलिरहेका थिए",Impact,6,0.054545,110,110,1
1,i_econ_stop_business,2,"Yes, temporarily stopped operations","हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो",Impact,85,0.772727,110,110,2
2,i_econ_stop_business,3,"Yes, permanently stopped","हो, स्थायी रूपमा रोकियो",Impact,19,0.172727,110,110,3
3,i_econ_stop_business_how_lng,1,Less than a month,एक महिना भन्दा कम,Impact,2,0.023529,85,110,4
4,i_econ_stop_business_how_lng,2,1 to 3 months,१-३ महिना,Impact,5,0.058824,85,110,5

In [112]:
class Bivariate():
    def __init__(self, raw_data, variable_map, labels_map, groupby_columns):
        self.raw_data = raw_data
        self.variable_map = variable_map
        self.labels_map = labels_map
        self.groupby_columns = groupby_columns
        self.selected_variables = self.variable_map[self.variable_map['selected'] ==1]
        self.labels_map['variable_label'] = self.variable_value(self.labels_map['variable'], self.labels_map['value'])
        self.s_select_variables = self.selected_variables[self.selected_variables['input_type'] == 'single-select']['variable'].values.tolist()
        self.m_select_variables = self.selected_variables[self.selected_variables['input_type'] == 'multi-select']['variable'].values.tolist()

    def generate_singleselect(self):
        s_select_bivariate_variables = self.s_select_variables + self.groupby_columns
        s_select_raw = self.raw_data[s_select_bivariate_variables]
        s_select_bivariate = []
        for x_variable in self.groupby_columns:
            for y_variable in self.s_select_variables:
                xy_tuple = self.create_xy_tuple(x_variable, y_variable)
                x_label_dict, y_label_dict = self.create_label_dict(x_variable, y_variable)
                s_select_each = self.s_select_generate_total(s_select_raw, x_variable, y_variable, xy_tuple)
                s_select_each = self.add_labels(s_select_each, x_label_dict, y_label_dict, x_variable, y_variable)
                if len(s_select_bivariate)==0:
                    s_select_bivariate = s_select_each
                else:
                    s_select_bivariate = pd.concat((s_select_bivariate, s_select_each))
        return s_select_bivariate
                
    
    def generate_multi_select(self):
        m_select_variable_label = self.selected_variables.set_index('variable').transpose()[list(self.m_select_variables)].transpose()['variable_label'].values.tolist()
        m_select_bivariate_labels = m_select_variable_label + self.groupby_columns
        m_select_raw = self.raw_data[m_select_bivariate_labels]
        
    
    def generate_bivariate(self):
        pass
    
    
    def create_xy_tuple(self, x_variable, y_variable):
        xy_tuple = []
        for i in self.labels_map[self.labels_map['variable'] == x_variable].value:
            for j in self.labels_map[self.labels_map['variable'] == y_variable].value:
                xy_tuple.append((i,j))
        return xy_tuple
    
    
    def create_label_dict(self, x_variable, y_variable):
        labels_list = ['value', 'label_en', 'label_ne', 'variable_group']
        x_label_dict = self.labels_map.loc[self.labels_map['variable']==x_variable][labels_list].set_index('value').to_dict()
        y_label_dict =  self.labels_map.loc[ self.labels_map['variable']==y_variable][labels_list].set_index('value').to_dict()
        return x_label_dict, y_label_dict
    
    
    def s_select_generate_total(self, s_select_raw, x_variable, y_variable, xy_tuple):
        s_select_each = pd.DataFrame(s_select_raw.groupby([x_variable])[y_variable].value_counts())
        s_select_each.columns = ['total']
        s_select_each = s_select_each.to_dict()
        for i in xy_tuple:
            if i not in s_select_each['total'].keys():
                s_select_each['total'][i] = 0
        s_select_each = pd.DataFrame(s_select_each)
        return s_select_each
    
    def add_labels(self, df, x_label_dict, y_label_dict, x_variable, y_variable):
        df.reset_index(inplace=True)
        df['x_variable'] = x_variable
        df['y_variable'] = y_variable
        df.columns = ['x_value', 'y_value', 'total', 'x_variable', 'y_variable']
        df['y_label_en'] = df['y_value'].apply(lambda x: y_label_dict['label_en'][x])
        df['y_label_ne'] = df['y_value'].apply(lambda x: y_label_dict['label_ne'][x])
        df['x_label_en'] = df['x_value'].apply(lambda x: x_label_dict['label_en'][x])
        df['x_label_ne'] = df['x_value'].apply(lambda x: x_label_dict['label_ne'][x])
        df['variable_group'] = y_label_dict['variable_group'][1]
        df = df[['x_variable', 'x_value', 'x_label_en','x_label_ne', 'y_variable', 'y_value','y_label_en','y_label_ne', 'total', 'variable_group']]
        return df
    
    def variable_value(self, variable, value):
        var_val = []
        for idx, var in enumerate(list(variable)):
            var_val.append(var+'__' + str(list(value)[idx]))
        return var_val

In [113]:
groupby_columns = ['m_biz_type', 'm_biz_years_in_operation', 'b_n_emplyes_pre_covid']
bivariate_ss = Bivariate(raw_data=business_raw_data, variable_map=business_variable_map, labels_map=business_labels_map, groupby_columns=groupby_columns )

In [114]:
bivariate_ss.generate_singleselect()

,x_variable,x_value,x_label_en,x_label_ne,y_variable,y_value,y_label_en,y_label_ne,total,variable_group
0,m_biz_type,1,Hotel,होटल,i_econ_stop_business,1.0,"No, operations were always running","होइन, अपरेशनहरू सँधै चलिरहेका थिए",5,Impact
1,m_biz_type,1,Hotel,होटल,i_econ_stop_business,2.0,"Yes, temporarily stopped operations","हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो",21,Impact
2,m_biz_type,1,Hotel,होटल,i_econ_stop_business,3.0,"Yes, permanently stopped","हो, स्थायी रूपमा रोकियो",3,Impact
3,m_biz_type,2,Restaurant and Bar,भोजनालय र बार,i_econ_stop_business,1.0,"No, operations were always running","होइन, अपरेशनहरू सँधै चलिरहेका थिए",0,Impact
4,m_biz_type,2,Restaurant and Bar,भोजनालय र बार,i_econ_stop_business,2.0,"Yes, temporarily stopped operations","हो, अस्थायी रूपमा सञ्चालनहरू बन्द गरियो",10,Impact
...,...,...,...,...,...,...,...,...,...,...
10,b_n_emplyes_pre_covid,4,51 to 100 people,५१-१०० जना,o_perm_stop_biz_start_new_job,2.0,"Yes, it is a tourism-related job","छु, यो एक पर्यटन सम्बन्धित काम हो",0,Outlook
11,b_n_emplyes_pre_covid,4,51 to 100 people,५१-१०० जना,o_perm_stop_biz_start_new_job,3.0,"Yes, but it is a non-tourism related job","छु, यो पर्यटन सम्बन्धित काम होइन",0,Outlook
12,b_n_emplyes_pre_covid,5,More than 100 people,१०० भन्दा बढी,o_perm_stop_biz_start_new_job,1.0,No,छैन,0,Outlook
13,b_n_emplyes_pre_covid,5,More than 100 people,१०० भन्दा बढी,o_perm_stop_biz_start_new_job,2.0,"Yes, it is a tourism-related job","छु, यो एक पर्यटन सम्बन्धित काम हो",0,Outlook
14,b_n_emplyes_pre_covid,5,More than 100 people,१०० भन्दा बढी,o_perm_stop_biz_start_new_job,3.0,"Yes, but it is a non-tourism related job","छु, यो पर्यटन सम्बन्धित काम होइन",0,Outlook