In [1]:
import pandas as pd
import numpy as np
import folium
from folium.plugins import HeatMap

In [20]:
business_df = pd.read_excel('../raw/business_data.xlsx')
variable_map = pd.read_excel('../data/map_viz_variable.xlsx')

In [3]:
business_df.head()

,m_start,m_end,m_today,m_username,m_deviceid,m_subscriberid,m_imei,m_phonenumber,_span_style_color_FF_finances_and_HR_span,i_econ_stop_business,...,__version__,_id,_uuid,_submission_time,_validation_status,_notes,_status,_submitted_by,_tags,_index
0,2021-04-28T15:14:45.949+05:45,2021-04-28T15:33:20.591+05:45,2021-04-28,username not found,ee.humanitarianresponse.info:efUjl6IoNb0tnOVO,subscriberid not found,ee.humanitarianresponse.info:efUjl6IoNb0tnOVO,phonenumber not found,NaN,2,...,vwGwixFVQLjhFdchggLZtd,174444706,510712d3-b5f6-47e7-b3d2-9ae5f49e3b94,2021-04-28T09:47:31,NaN,[],submitted_via_web,NaN,NaN,36
1,2021-05-07T10:59:17.820+05:45,2021-05-07T11:21:20.855+05:45,2021-05-07,username not found,ee.humanitarianresponse.info:ivuI8g0MlCGor6Ft,subscriberid not found,ee.humanitarianresponse.info:ivuI8g0MlCGor6Ft,phonenumber not found,NaN,2,...,vwGwixFVQLjhFdchggLZtd,176510702,8ff407ec-6aab-46c8-bb5b-cc48219cc389,2021-05-07T05:36:20,NaN,[],submitted_via_web,NaN,NaN,109
2,2021-04-26T17:28:00.072+05:45,2021-04-26T17:41:14.457+05:45,2021-04-26,username not found,ee.humanitarianresponse.info:0cXJ5kEGM9avnhKH,subscriberid not found,ee.humanitarianresponse.info:0cXJ5kEGM9avnhKH,phonenumber not found,NaN,2,...,vwGwixFVQLjhFdchggLZtd,173876161,fd294dd2-9126-4feb-9b54-a0d41843f063,2021-04-26T11:57:05,NaN,[],submitted_via_web,NaN,NaN,8
3,2021-05-01T08:07:51.848+05:45,2021-05-01T08:45:08.379+05:45,2021-05-01,username not found,ee.humanitarianresponse.info:RyUETda2QuZoNbud,subscriberid not found,ee.humanitarianresponse.info:RyUETda2QuZoNbud,phonenumber not found,NaN,2,...,vwGwixFVQLjhFdchggLZtd,175156051,76b937cb-67fb-4892-ac32-5ec77e023929,2021-05-01T03:00:10,NaN,[],submitted_via_web,NaN,NaN,69
4,2021-05-16T19:46:28.056+05:45,2021-05-16T20:06:45.761+05:45,2021-05-16,username not found,ee.humanitarianresponse.info:CS5rQbmD3nN55q2y,subscriberid not found,ee.humanitarianresponse.info:CS5rQbmD3nN55q2y,phonenumber not found,NaN,2,...,vwGwixFVQLjhFdchggLZtd,178003908,d9cfe125-2298-41e8-bdd8-17e7262ebbdb,2021-05-16T14:21:47,NaN,[],submitted_via_web,NaN,NaN,110

In [4]:
business_map_df = business_df[['m_name_business', 'm_today', 'm_coodinates']]
business_map_df = business_map_df[business_map_df['m_coodinates']!=' ']

In [5]:
business_map_df['coordinates'] = business_map_df['m_coodinates'].apply(func= lambda x: (float(x.split(' ')[0]), float(x.split(' ')[1])))
business_map_df.drop('m_coodinates', axis=1, inplace=True)

In [6]:
business_map_df.head()

,m_name_business,m_today,coordinates
0,Shisha Lounge & Bar Pvt Ltd,2021-04-28,"(27.7153038584918, 85.3103238891712)"
1,Hotel Vinayak pvt ltd,2021-05-07,"(26.98806, 85.89996)"
2,chitwan forest resort,2021-04-26,"(27.58148, 84.49332)"
3,Suburb cafe,2021-05-01,"(27.684759, 85.312688)"
4,hostel nextdoor,2021-05-16,"(27.684944, 85.315922)"

In [23]:
selected_variables = variable_map[variable_map['selected']=='yes']
s_select_variables = selected_variables[selected_variables['input_type']=='single-select']['variable'].tolist()
multi_select_variables = selected_variables[selected_variables['input_type']=='multi-select']['variable'].tolist()

In [25]:
s_select_variables

,variable,ques_en,ques_ne,group,asked_condition,highlights,selected,Suggestions,input_type
0,i_econ_stop_business,Did you have to stop your business due to COVI...,के तपाईंले कोभिड-१९ महामारीको कारण आफ्नो व्यवस...,impact,general,....% of businesses had to shut down permanently.,yes,NaN,single-select
1,i_econ_stop_business_how_lng,For how long did you have to stop your business?,कति समय सम्म तपाईंले आफ्नो व्यापार बन्द गर्नु ...,impact,business temporarily stopped,......% of businesses' operations was disrupte...,yes,NaN,single-select
22,i_wrkfrc_size_chng_2020_v_2019,"Compared to 2019, how has the size of your wor...",२०१९को तुलानामा महमारिको कारणले २०२० मा तपाईंक...,impact,general,NaN,yes,businesses which reduced staff by 50% or more,single-select
23,i_fin_revenue_chng_2020_v_2019,"Compared to 2019, how have your business reven...",२०१९को तुलानामा महमारिको कारणले २०२० मा तपाईंक...,impact,general,NaN,yes,curious to see how this will be shown,single-select
24,i_fin_savings_chng_2020_v_2019,"Compared to 2019, how has your business’s savi...",२०१९को तुलानामा महमारिको कारणले २०२० मा तपाईंक...,impact,general,NaN,yes,businesses whose savings reduced by 50% or more,single-select
41,n_rcvry_preferred_loan_pybck_incntv,Which of the following loan payback-related as...,निम्न मध्ये कुन ऋण रकम फिर्ता सम्बन्धीत सहयोग ...,need,business will have difficulties in paying back...,NaN,yes,NaN,single-select
42,n_rcvry_preferred_fund_aprvl_incntv,Which of the following funds-related assistanc...,तलका कोषहरू सम्बन्धित कुन मद्दत तपाईंलाई सबैभन...,need,business will have difficulties to acquire add...,NaN,yes,NaN,single-select
43,n_rcvry_preferred_fin_source,What is your preferred source (first choice) o...,तपाईंको व्यावसायको लागि निम्न आर्थिक स्रोत मध्...,need,business will have difficulties to acquire add...,NaN,yes,NaN,single-select
45,n_rcvry_preferred_tax_asstnc,Which of the following tax-related assistance ...,तलका करहरू सम्बन्धित कुन मद्दत तपाईंलाई सबैभन्...,need,business will have difficulties in paying its ...,NaN,yes,NaN,single-select
46,n_rcvry_preferred_tax_asstn_other,Which of the following operating costs-related...,निम्न मध्ये कुन अपरेटिंग लागत सम्बन्धित सहयोग ...,need,business will have difficulties in covering it...,NaN,yes,NaN,single-select
47,n_rcvry_preferred_labor_asstnc,Which of the following labor-related assistanc...,निम्न मध्ये कुन श्रम सम्बन्धी सहयोग तपाईंलाई स...,need,business will most likely face labor-related i...,NaN,yes,NaN,single-select
48,n_rcvry_preferred_outreach_other,Which of the following business outreach-relat...,निम्न मध्ये कुन व्यापार आउटरीच सम्बन्धित सहयोग...,need,business will have difficulties in getting eno...,NaN,yes,NaN,single-select
49,o_do_u_know_of_gov_schemes,The government has announced different schemes...,पर्यटन व्यवसायको पुनरुद्धारका लागि सरकारले विभ...,need,general,NaN,yes,NaN,single-select
53,o_covid_how_long_it_last,How much longer do you expect the disruption d...,महामारीको कारणले भएको विघटन कति लामो हुने आशा ...,outlook,general,NaN,yes,NaN,single-select
54,o_econ_impact_revenue_chng_21_v_19,"Compared to 2019, how much revenues does your ...",२०१९को तुलानामा २०२१मा तपाईंको व्यवसायले कति र...,outlook,general,NaN,yes,NaN,single-select
55,o_econ_impact_wrkfrc_chng_21_v_19,"Compared to 2019, what percentage of workforce...",२०१९को तुलानामा २०२१मा तपाईंको व्यवसायले कति प...,outlook,general,NaN,yes,businesses that hope to retain near 2019 emplo...,single-select
61,o_rcvry_biggest_support,Who do you think will be the biggest support f...,तपाईको व्यवसायको लागी सब भन्दा ठूलो सहयोगी को ...,outlook,general,NaN,yes,NaN,single-select
64,o_perm_stop_biz_future_retrn_trsm_biz,Do you intend to return to the tourism busines...,के तपाइँ भविष्यमा पर्यटन व्यवसायमा फर्कनु हुनेछ ?,outlook,NaN,NaN,yes,businesses that have decided to quit tourism,single-select

In [24]:
for i in s_select_variables:
    print(i)
#     each_var_df = business_df[['m_name_business', 'm_today', 'm_coodinates']]
#     each_var_df = each_var_df[each_var_df['m_coodinates']!=' ']
#     each_var_df['coordinates'] = each_var_df['m_coodinates'].apply(func= lambda x: (float(x.split(' ')[0]), float(x.split(' ')[1])))
#     each_var_df.drop('m_coodinates', axis=1, inplace=True)
#     each_var_df['variable'] = i
#     each_var_df['value'] = business_df[i]

KeyError: 'variable'

In [8]:
each_var_df

,m_name_business,m_today,coordinates,variable,value
0,Shisha Lounge & Bar Pvt Ltd,2021-04-28,"(27.7153038584918, 85.3103238891712)",i_econ_stop_business,2
1,Hotel Vinayak pvt ltd,2021-05-07,"(26.98806, 85.89996)",i_econ_stop_business,2
2,chitwan forest resort,2021-04-26,"(27.58148, 84.49332)",i_econ_stop_business,2
3,Suburb cafe,2021-05-01,"(27.684759, 85.312688)",i_econ_stop_business,2
4,hostel nextdoor,2021-05-16,"(27.684944, 85.315922)",i_econ_stop_business,2
...,...,...,...,...,...
107,Thamel Seasons Hotel Pvt.ltd,2021-05-02,"(27.7179141297178, 85.3101209550944)",i_econ_stop_business,3
108,Hotel Business,2021-05-03,"(27.6632585317559, 85.4449016109137)",i_econ_stop_business,2
109,The freedom cafe restaurant & bar,2021-05-05,"(28.2209793, 83.9559105)",i_econ_stop_business,3
110,Tour and trekking and Expedition,2021-05-06,"(27.7153213473598, 85.3117415550944)",i_econ_stop_business,2
111,Outlandish Nepal Holidays Ltd.,2021-05-26,"(27.6742617216237, 85.3691647550934)",i_econ_stop_business,2

In [21]:
base_map = folium.Map(location=[27.7, 85.3240], zoom_start=13)
HeatMap(data=business_map_df['coordinates'], radius=9, max_zoom=13, ).add_to(base_map)
# base_map.save('kirana_heatmap.html')
base_map